# -*- coding: utf-8 -*-
"""colab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwutQfP_gY2-UKG1CPdiDtZXIiO5rItl
"""

import pandas as pd
import numpy as np

#dataset = pd.read_csv("/content/IGN_reviews.csv")
dataset = pd.read_csv("IGN_reviews.csv")

dataframe = pd.DataFrame(dataset)
print(dataframe)

dataframe.head(1)

dataframe.tail(2)

dataframe.info()

_dataframe = dataframe.isnull()
_dataframe

_dataframe.sum()

new_dataframe=dataframe.dropna()
new_dataframe

new_dataframe.to_csv("reviews_non-nulled.csv")